server:
  port: 2333
spring:
  application:
    name: nicholas_house
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ning.nicholas_house.entity.dobean
